#!/bin/sh
set -e
echo 'Installing program : local-prune.sh .....'
cd /usr/bin/
sudo shc -f local-prune.sh || exit
sudo mv local-prune.sh.x local-prune
sudo rm local-prune.sh
sudo rm local-prune.sh.x.c
